//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UACHelper.Sample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UACHelper.Sample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Restart.
        /// </summary>
        internal static string MainForm_Restart_Caption {
            get {
                return ResourceManager.GetString("MainForm_Restart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the changes to take effect, you need to restart your computer. Do you want to continue?.
        /// </summary>
        internal static string MainForm_Restart_Message {
            get {
                return ResourceManager.GetString("MainForm_Restart_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Asking.
        /// </summary>
        internal static string MainForm_ShowGoodies_MessageBox_Caption {
            get {
                return ResourceManager.GetString("MainForm_ShowGoodies_MessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a sample MessageBox demonstrating the `WinForm.ShieldifyDialog` method. Enjoying?.
        /// </summary>
        internal static string MainForm_ShowGoodies_MessageBox_Message {
            get {
                return ResourceManager.GetString("MainForm_ShowGoodies_MessageBox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string MainForm_ShowGoodies_Result_Caption {
            get {
                return ResourceManager.GetString("MainForm_ShowGoodies_Result_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; button Clicked..
        /// </summary>
        internal static string MainForm_ShowGoodies_Result_Message {
            get {
                return ResourceManager.GetString("MainForm_ShowGoodies_Result_Message", resourceCulture);
            }
        }
    }
}
